import { IntentConfig, IntentParameter } from '../types';

/**
 * Generates the Swift source containing one `AppIntent` struct per declared intent plus an
 * `AppShortcutsProvider` that registers them with Siri / Spotlight.
 *
 * App Intents metadata is extracted by the compiler, so these structs must exist at build time.
 * Each `perform()` defers its logic to `ExpoIntentsRunner.shared.perform(handler:params:)`, which
 * runs the JS handler registered under the same `name`.
 */
export function generateIntentsSwift(intents: IntentConfig[], appName: string): string {
  // `internal import` matches Expo's generated ExpoModulesProvider.swift, which is compiled into
  // the same app target. Mixing an explicit access level there with a bare `import` here trips
  // Swift's access-level-on-imports ambiguity diagnostic.
  const header = `// @generated by expo-intents config plugin. Do NOT edit.
import AppIntents
internal import ExpoIntents
`;

  if (intents.length === 0) {
    return `${header}
// No intents were declared in the expo-intents config plugin options.
`;
  }

  const structs = intents.map((intent) => generateIntentStruct(intent)).join('\n\n');
  const shortcuts = generateShortcutsProvider(intents, appName);

  return `${header}\n${structs}\n\n${shortcuts}\n`;
}

function structName(intent: IntentConfig): string {
  const base = intent.name.replace(/[^A-Za-z0-9]/g, ' ');
  const pascal = base
    .split(' ')
    .filter(Boolean)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join('');
  return `${pascal}Intent`;
}

function generateIntentStruct(intent: IntentConfig): string {
  const parameters = intent.parameters ?? [];
  const description = intent.description
    ? `  static var description = IntentDescription(${swiftString(intent.description)})\n`
    : '';

  const parameterDecls = parameters.map(generateParameterDecl).join('\n');
  const paramsEntries = parameters.map((p) => `"${p.name}": ${p.name}`).join(', ');
  const paramsLiteral = parameters.length ? `[${paramsEntries}]` : '[:]';

  return `@available(iOS 16.4, *)
struct ${structName(intent)}: AppIntent {
  static var title: LocalizedStringResource = ${swiftString(intent.title)}
${description}${parameterDecls ? parameterDecls + '\n' : ''}
  func perform() async throws -> some IntentResult & ReturnsValue<String> {
    let params: [String: Any] = ${paramsLiteral}
    let result = try await ExpoIntentsRunner.shared.perform(handler: ${swiftString(
      intent.name
    )}, params: params)
    return .result(value: result)
  }
}`;
}

function generateParameterDecl(parameter: IntentParameter): string {
  const title = parameter.title ?? parameter.name;
  return `  @Parameter(title: ${swiftString(title)})\n  var ${parameter.name}: ${swiftType(
    parameter.type
  )}`;
}

/** Maps an intent parameter type to its Swift `@Parameter` type. JS numbers are always doubles. */
function swiftType(type: IntentParameter['type']): string {
  switch (type) {
    case 'number':
      return 'Double';
    case 'boolean':
      return 'Bool';
    case 'string':
    default:
      return 'String';
  }
}

function generateShortcutsProvider(intents: IntentConfig[], appName: string): string {
  const entries = intents
    .filter((intent) => (intent.phrases ?? []).length > 0)
    .map((intent) => {
      const phrases = (intent.phrases ?? [])
        .map((phrase) => swiftPhrase(phrase, appName))
        .join(',\n        ');
      return `      AppShortcut(
        intent: ${structName(intent)}(),
        phrases: [
        ${phrases}
        ]
      )`;
    })
    .join('\n');

  if (!entries) {
    return `// No AppShortcut phrases were declared, so no AppShortcutsProvider was generated.`;
  }

  return `@available(iOS 16.4, *)
struct ExpoIntentsAppShortcuts: AppShortcutsProvider {
  static var appShortcuts: [AppShortcut] {
${entries}
  }
}`;
}

/** Builds an AppShortcut phrase literal, mapping the `${applicationName}` placeholder. */
function swiftPhrase(phrase: string, _appName: string): string {
  const segments = phrase.split('${applicationName}');
  const interpolated = segments
    .map((segment) => escapeSwift(segment))
    .join('\\(.applicationName)');
  return `"${interpolated}"`;
}

function swiftString(value: string): string {
  return `"${escapeSwift(value)}"`;
}

function escapeSwift(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}
