import { IntentConfig, IntentEnumChoice, IntentParameter } from '../types';

/**
 * Generates the Swift source containing one `AppIntent` struct per declared intent, any `AppEnum`
 * types backing `enum` parameters, plus an `AppShortcutsProvider` that registers them with
 * Siri / Spotlight.
 *
 * App Intents metadata is extracted by the compiler, so these structs must exist at build time.
 * Each `perform()` defers its logic to `ExpoIntentsRunner.shared.perform(handler:params:)`, which
 * runs the JS handler registered under the same `name`.
 */
export function generateIntentsSwift(intents: IntentConfig[], appName: string): string {
  // `internal import` matches Expo's generated ExpoModulesProvider.swift, which is compiled into
  // the same app target. Mixing an explicit access level there with a bare `import` here trips
  // Swift's access-level-on-imports ambiguity diagnostic.
  const header = `// @generated by expo-intents config plugin. Do NOT edit.
import AppIntents
import Foundation
internal import ExpoIntents
`;

  if (intents.length === 0) {
    return `${header}
// No intents were declared in the expo-intents config plugin options.
`;
  }

  const enums = generateEnums(intents);
  const structs = intents.map((intent) => generateIntentStruct(intent)).join('\n\n');
  const shortcuts = generateShortcutsProvider(intents, appName);

  const sections = [header, ...enums, structs, shortcuts].filter(Boolean);
  return `${sections.join('\n\n')}\n`;
}

// MARK: - Intent structs

function structName(intent: IntentConfig): string {
  return `${pascal(intent.name)}Intent`;
}

function generateIntentStruct(intent: IntentConfig): string {
  const parameters = intent.parameters ?? [];
  const description = intent.description
    ? `  static var description = IntentDescription(${swiftString(intent.description)})\n`
    : '';

  const parameterDecls = parameters.map((p) => generateParameterDecl(intent, p)).join('\n');
  const paramsEntries = parameters
    .map((p) => `${swiftString(p.name)}: ${paramValueExpr(p)}`)
    .join(', ');
  const paramsLiteral = parameters.length ? `[${paramsEntries}]` : '[:]';

  return `@available(iOS 16.4, *)
struct ${structName(intent)}: AppIntent {
  static var title: LocalizedStringResource = ${swiftString(intent.title)}
${description}${parameterDecls ? parameterDecls + '\n' : ''}
  func perform() async throws -> some IntentResult & ReturnsValue<String> {
    let params: [String: Any] = ${paramsLiteral}
    let result = try await ExpoIntentsRunner.shared.perform(handler: ${swiftString(
      intent.name
    )}, params: params)
    return .result(value: result)
  }
}`;
}

function generateParameterDecl(intent: IntentConfig, parameter: IntentParameter): string {
  const title = parameter.title ?? parameter.name;
  const args = [`title: ${swiftString(title)}`];
  if (parameter.default !== undefined) {
    args.push(`default: ${swiftDefault(intent, parameter)}`);
  }
  return `  @Parameter(${args.join(', ')})\n  var ${parameter.name}: ${swiftParamType(
    intent,
    parameter
  )}`;
}

/** The Swift `@Parameter` type for a parameter, including the trailing `?` for optionals. */
function swiftParamType(intent: IntentConfig, parameter: IntentParameter): string {
  let base: string;
  switch (parameter.type) {
    case 'number':
      base = 'Double';
      break;
    case 'boolean':
      base = 'Bool';
      break;
    case 'date':
      base = 'Date';
      break;
    case 'enum':
      base = enumTypeName(intent, parameter);
      break;
    case 'string':
    default:
      base = 'String';
  }
  return isOptional(parameter) ? `${base}?` : base;
}

/** A parameter is optional only when explicitly marked and without a default (default ⇒ present). */
function isOptional(parameter: IntentParameter): boolean {
  return parameter.optional === true && parameter.default === undefined;
}

/**
 * The Swift expression placed in the `params` dictionary passed to the JS handler.
 *
 * Optionals collapse to `Any` via `.map { … as Any } ?? NSNull()` — `x ?? NSNull()` alone would
 * not type-check (the `??` operands must share a type). JavaScriptCore bridges `Date` → JS `Date`
 * and `NSNull` → `null`.
 */
function paramValueExpr(parameter: IntentParameter): string {
  const name = parameter.name;
  const isEnum = parameter.type === 'enum';
  if (isOptional(parameter)) {
    const mapped = isEnum ? `$0.rawValue as Any` : `$0 as Any`;
    return `${name}.map { ${mapped} } ?? NSNull()`;
  }
  // Pass the enum's String rawValue (the underlying choice value) to JS; others pass directly.
  return isEnum ? `${name}.rawValue` : name;
}

function swiftDefault(intent: IntentConfig, parameter: IntentParameter): string {
  const value = parameter.default;
  switch (parameter.type) {
    case 'number':
      return String(value);
    case 'boolean':
      return value ? 'true' : 'false';
    case 'date':
      throw new Error(
        `expo-intents: parameter "${parameter.name}" of intent "${intent.name}" is a date and cannot have a default.`
      );
    case 'enum': {
      const choice = normalizeChoices(intent, parameter).find((c) => c.value === value);
      if (!choice) {
        throw new Error(
          `expo-intents: default "${String(value)}" for enum parameter "${parameter.name}" of intent "${intent.name}" is not one of its choices.`
        );
      }
      return `.${choice.caseName}`;
    }
    case 'string':
    default:
      return swiftString(String(value));
  }
}

// MARK: - Enums (AppEnum)

type NormalizedChoice = { caseName: string; value: string; title: string };

function enumTypeName(intent: IntentConfig, parameter: IntentParameter): string {
  return `${pascal(intent.name)}${pascal(parameter.name)}AppEnum`;
}

function normalizeChoices(intent: IntentConfig, parameter: IntentParameter): NormalizedChoice[] {
  const choices = parameter.choices ?? [];
  if (choices.length === 0) {
    throw new Error(
      `expo-intents: enum parameter "${parameter.name}" of intent "${intent.name}" requires a non-empty "choices" array.`
    );
  }
  const used = new Set<string>();
  return choices.map((choice: IntentEnumChoice, index: number) => {
    const value = typeof choice === 'string' ? choice : choice.value;
    const title = typeof choice === 'string' ? choice : choice.title ?? choice.value;
    let caseName = safeCaseName(value) || `case${index}`;
    let candidate = caseName;
    let suffix = 1;
    while (used.has(candidate)) {
      candidate = `${caseName}${suffix++}`;
    }
    used.add(candidate);
    return { caseName: candidate, value, title };
  });
}

function generateEnums(intents: IntentConfig[]): string[] {
  const blocks: string[] = [];
  for (const intent of intents) {
    for (const parameter of intent.parameters ?? []) {
      if (parameter.type !== 'enum') {
        continue;
      }
      const typeName = enumTypeName(intent, parameter);
      const choices = normalizeChoices(intent, parameter);
      const cases = choices.map((c) => `  case ${c.caseName} = ${swiftString(c.value)}`).join('\n');
      const displays = choices
        .map((c) => `    .${c.caseName}: ${swiftString(c.title)}`)
        .join(',\n');
      blocks.push(`@available(iOS 16.4, *)
enum ${typeName}: String, AppEnum {
${cases}

  static var typeDisplayRepresentation: TypeDisplayRepresentation = ${swiftString(
    parameter.title ?? parameter.name
  )}
  static var caseDisplayRepresentations: [${typeName}: DisplayRepresentation] = [
${displays}
  ]
}`);
    }
  }
  return blocks;
}

// MARK: - App Shortcuts

function generateShortcutsProvider(intents: IntentConfig[], appName: string): string {
  const entries = intents
    .filter((intent) => (intent.phrases ?? []).length > 0)
    .map((intent) => {
      const phrases = (intent.phrases ?? [])
        .map((phrase) => swiftPhrase(phrase, appName))
        .join(',\n        ');
      return `      AppShortcut(
        intent: ${structName(intent)}(),
        phrases: [
        ${phrases}
        ]
      )`;
    })
    .join('\n');

  if (!entries) {
    return `// No AppShortcut phrases were declared, so no AppShortcutsProvider was generated.`;
  }

  return `@available(iOS 16.4, *)
struct ExpoIntentsAppShortcuts: AppShortcutsProvider {
  static var appShortcuts: [AppShortcut] {
${entries}
  }
}`;
}

/** Builds an AppShortcut phrase literal, mapping the `${applicationName}` placeholder. */
function swiftPhrase(phrase: string, _appName: string): string {
  const segments = phrase.split('${applicationName}');
  const interpolated = segments
    .map((segment) => escapeSwift(segment))
    .join('\\(.applicationName)');
  return `"${interpolated}"`;
}

// MARK: - String helpers

function pascal(value: string): string {
  return value
    .replace(/[^A-Za-z0-9]+/g, ' ')
    .split(' ')
    .filter(Boolean)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join('');
}

/** A valid Swift enum case identifier derived from a choice value (backtick-escaped if reserved). */
function safeCaseName(value: string): string {
  const words = value.replace(/[^A-Za-z0-9]+/g, ' ').trim().split(' ').filter(Boolean);
  let name = words
    .map((word, i) => (i === 0 ? word.charAt(0).toLowerCase() : word.charAt(0).toUpperCase()) + word.slice(1))
    .join('');
  if (!name) {
    return '';
  }
  if (/^[0-9]/.test(name)) {
    name = `_${name}`;
  }
  return SWIFT_KEYWORDS.has(name) ? `\`${name}\`` : name;
}

const SWIFT_KEYWORDS = new Set([
  'associatedtype', 'class', 'deinit', 'enum', 'extension', 'fileprivate', 'func', 'import',
  'init', 'inout', 'internal', 'let', 'open', 'operator', 'private', 'protocol', 'public',
  'rethrows', 'static', 'struct', 'subscript', 'typealias', 'var', 'break', 'case', 'continue',
  'default', 'defer', 'do', 'else', 'fallthrough', 'for', 'guard', 'if', 'in', 'repeat', 'return',
  'switch', 'where', 'while', 'as', 'catch', 'false', 'is', 'nil', 'super', 'self', 'throw',
  'throws', 'true', 'try', 'any', 'some',
]);

function swiftString(value: string): string {
  return `"${escapeSwift(value)}"`;
}

function escapeSwift(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}
